curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/adm_grenzen_2005.map&request=getcapabilities&service=wms&version=1.1.53'|grep-vdefault|grepName>adm_grenzen_2005.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/adm_grenzen_2010.map&request=getcapabilities&service=wms&version=1.1.52'|grep-vdefault|grepName>adm_grenzen_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/adm_grenzen_overig.map&request=getcapabilities&service=wms&version=1.1.51'|grep-vdefault|grepName>adm_grenzen_overig.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/AmerikaWeek.map&request=getcapabilities&service=wms&version=1.1.50'|grep-vdefault|grepName>AmerikaWeek.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/amsterdam1745.map&request=getcapabilities&service=wms&version=1.1.49'|grep-vdefault|grepName>amsterdam1745.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/andes.map&request=getcapabilities&service=wms&version=1.1.48'|grep-vdefault|grepName>andes.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/athene.map&request=getcapabilities&service=wms&version=1.1.47'|grep-vdefault|grepName>athene.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bag_aggregaties.map&request=getcapabilities&service=wms&version=1.1.46'|grep-vdefault|grepName>bag_aggregaties.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bag.map&request=getcapabilities&service=wms&version=1.1.45'|grep-vdefault|grepName>bag.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/base_all_visible.map&request=getcapabilities&service=wms&version=1.1.44'|grep-vdefault|grepName>base_all_visible.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/base_combined.map&request=getcapabilities&service=wms&version=1.1.43'|grep-vdefault|grepName>base_combined.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/base_debug.map&request=getcapabilities&service=wms&version=1.1.42'|grep-vdefault|grepName>base_debug.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/base.map&request=getcapabilities&service=wms&version=1.1.41'|grep-vdefault|grepName>base.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/basetest1.map&request=getcapabilities&service=wms&version=1.1.40'|grep-vdefault|grepName>basetest1.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/basetest.map&request=getcapabilities&service=wms&version=1.1.39'|grep-vdefault|grepName>basetest.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_arbeid.map&request=getcapabilities&service=wms&version=1.1.38'|grep-vdefault|grepName>bevolking_arbeid.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_herkomst_2010.map&request=getcapabilities&service=wms&version=1.1.37'|grep-vdefault|grepName>bevolking_herkomst_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_herkomst2.map&request=getcapabilities&service=wms&version=1.1.36'|grep-vdefault|grepName>bevolking_herkomst2.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_herkomst.map&request=getcapabilities&service=wms&version=1.1.35'|grep-vdefault|grepName>bevolking_herkomst.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_huishoudens_2010.map&request=getcapabilities&service=wms&version=1.1.34'|grep-vdefault|grepName>bevolking_huishoudens_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_huishoudens.map&request=getcapabilities&service=wms&version=1.1.33'|grep-vdefault|grepName>bevolking_huishoudens.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_investering_2005.map&request=getcapabilities&service=wms&version=1.1.32'|grep-vdefault|grepName>bevolking_investering_2005.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_leeftijd_02.map&request=getcapabilities&service=wms&version=1.1.31'|grep-vdefault|grepName>bevolking_leeftijd_02.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_leeftijd_2010.map&request=getcapabilities&service=wms&version=1.1.30'|grep-vdefault|grepName>bevolking_leeftijd_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolking_leeftijd.map&request=getcapabilities&service=wms&version=1.1.29'|grep-vdefault|grepName>bevolking_leeftijd.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolkings_dichtheid_2010.map&request=getcapabilities&service=wms&version=1.1.28'|grep-vdefault|grepName>bevolkings_dichtheid_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bevolkings_dichtheid.map&request=getcapabilities&service=wms&version=1.1.27'|grep-vdefault|grepName>bevolkings_dichtheid.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bioscopen.map&request=getcapabilities&service=wms&version=1.1.26'|grep-vdefault|grepName>bioscopen.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/blaeu.map&request=getcapabilities&service=wms&version=1.1.25'|grep-vdefault|grepName>blaeu.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/bodem.map&request=getcapabilities&service=wms&version=1.1.24'|grep-vdefault|grepName>bodem.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/cbs_bodemgebruik.map&request=getcapabilities&service=wms&version=1.1.23'|grep-vdefault|grepName>cbs_bodemgebruik.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/cbs.map&request=getcapabilities&service=wms&version=1.1.22'|grep-vdefault|grepName>cbs.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/china.map&request=getcapabilities&service=wms&version=1.1.21'|grep-vdefault|grepName>china.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/data.map&request=getcapabilities&service=wms&version=1.1.20'|grep-vdefault|grepName>data.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/deforestaction.map&request=getcapabilities&service=wms&version=1.1.19'|grep-vdefault|grepName>deforestaction.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/dnahn.map&request=getcapabilities&service=wms&version=1.1.18'|grep-vdefault|grepName>dnahn.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/dynahn.map&request=getcapabilities&service=wms&version=1.1.17'|grep-vdefault|grepName>dynahn.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_corine.map&request=getcapabilities&service=wms&version=1.1.16'|grep-vdefault|grepName>eu_corine.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_demografie.map&request=getcapabilities&service=wms&version=1.1.15'|grep-vdefault|grepName>eu_demografie.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_nuts_bevolkingsdichtheid_level_0.map&request=getcapabilities&service=wms&version=1.1.14'|grep-vdefault|grepName>eu_nuts_bevolkingsdichtheid_level_0.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_nuts_bevolkingsdichtheid_level_1.map&request=getcapabilities&service=wms&version=1.1.13'|grep-vdefault|grepName>eu_nuts_bevolkingsdichtheid_level_1.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_nuts_bevolkingsdichtheid_level_2.map&request=getcapabilities&service=wms&version=1.1.12'|grep-vdefault|grepName>eu_nuts_bevolkingsdichtheid_level_2.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_nuts_bevolkingsdichtheid_level_3.map&request=getcapabilities&service=wms&version=1.1.11'|grep-vdefault|grepName>eu_nuts_bevolkingsdichtheid_level_3.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/eu_nuts_regio_2010.map&request=getcapabilities&service=wms&version=1.1.10'|grep-vdefault|grepName>eu_nuts_regio_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/europa.map&request=getcapabilities&service=wms&version=1.1.9'|grep-vdefault|grepName>europa.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/gebieden_speciale_status.map&request=getcapabilities&service=wms&version=1.1.8'|grep-vdefault|grepName>gebieden_speciale_status.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/gemeenten_historisch.map&request=getcapabilities&service=wms&version=1.1.7'|grep-vdefault|grepName>gemeenten_historisch.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/geologie.map&request=getcapabilities&service=wms&version=1.1.6'|grep-vdefault|grepName>geologie.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/HistorischWereldwijd.map&request=getcapabilities&service=wms&version=1.1.5'|grep-vdefault|grepName>HistorischWereldwijd.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/hoogte2.map&request=getcapabilities&service=wms&version=1.1.4'|grep-vdefault|grepName>hoogte2.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/hoogte.map&request=getcapabilities&service=wms&version=1.1.3'|grep-vdefault|grepName>hoogte.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/ibag.map&request=getcapabilities&service=wms&version=1.1.2'|grep-vdefault|grepName>ibag.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/index.map&request=getcapabilities&service=wms&version=1.1.1'|grep-vdefault|grepName>index.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/kadasterdev.map&request=getcapabilities&service=wms&version=1.1.0'|grep-vdefault|grepName>kadasterdev.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/kadaster.map&request=getcapabilities&service=wms&version=1.1.1'|grep-vdefault|grepName>kadaster.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/kadaster_temp.map&request=getcapabilities&service=wms&version=1.1.2'|grep-vdefault|grepName>kadaster_temp.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/kyrgyzstan.map&request=getcapabilities&service=wms&version=1.1.3'|grep-vdefault|grepName>kyrgyzstan.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/landbouw_2010.map&request=getcapabilities&service=wms&version=1.1.4'|grep-vdefault|grepName>landbouw_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/landbouw.map&request=getcapabilities&service=wms&version=1.1.5'|grep-vdefault|grepName>landbouw.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/landschappen.map&request=getcapabilities&service=wms&version=1.1.6'|grep-vdefault|grepName>landschappen.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/lus.map&request=getcapabilities&service=wms&version=1.1.7'|grep-vdefault|grepName>lus.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/milieu.map&request=getcapabilities&service=wms&version=1.1.8'|grep-vdefault|grepName>milieu.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/monumenten.map&request=getcapabilities&service=wms&version=1.1.9'|grep-vdefault|grepName>monumenten.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/nkn.map&request=getcapabilities&service=wms&version=1.1.10'|grep-vdefault|grepName>nkn.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/noordzee.map&request=getcapabilities&service=wms&version=1.1.11'|grep-vdefault|grepName>noordzee.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/notaruimte.map&request=getcapabilities&service=wms&version=1.1.12'|grep-vdefault|grepName>notaruimte.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/nuts.map&request=getcapabilities&service=wms&version=1.1.13'|grep-vdefault|grepName>nuts.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/overstromingsschade.map&request=getcapabilities&service=wms&version=1.1.14'|grep-vdefault|grepName>overstromingsschade.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/population.map&request=getcapabilities&service=wms&version=1.1.15'|grep-vdefault|grepName>population.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/poverty.map&request=getcapabilities&service=wms&version=1.1.16'|grep-vdefault|grepName>poverty.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/provincies_inwoners.map&request=getcapabilities&service=wms&version=1.1.17'|grep-vdefault|grepName>provincies_inwoners.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/suriname.map&request=getcapabilities&service=wms&version=1.1.18'|grep-vdefault|grepName>suriname.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/thematisch.map&request=getcapabilities&service=wms&version=1.1.19'|grep-vdefault|grepName>thematisch.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/tim.map&request=getcapabilities&service=wms&version=1.1.20'|grep-vdefault|grepName>tim.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/verkiezingen_2010.map&request=getcapabilities&service=wms&version=1.1.21'|grep-vdefault|grepName>verkiezingen_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/verkiezingen_2012.map&request=getcapabilities&service=wms&version=1.1.22'|grep-vdefault|grepName>verkiezingen_2012.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/verkiezingen.map&request=getcapabilities&service=wms&version=1.1.23'|grep-vdefault|grepName>verkiezingen.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_auto_legenda.map&request=getcapabilities&service=wms&version=1.1.24'|grep-vdefault|grepName>voorzieningen_auto_legenda.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_bso.map&request=getcapabilities&service=wms&version=1.1.25'|grep-vdefault|grepName>voorzieningen_bso.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_fiets_legenda.map&request=getcapabilities&service=wms&version=1.1.26'|grep-vdefault|grepName>voorzieningen_fiets_legenda.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_onderwijs.map&request=getcapabilities&service=wms&version=1.1.27'|grep-vdefault|grepName>voorzieningen_onderwijs.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_ov.map&request=getcapabilities&service=wms&version=1.1.28'|grep-vdefault|grepName>voorzieningen_ov.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_wandel_legenda.map&request=getcapabilities&service=wms&version=1.1.29'|grep-vdefault|grepName>voorzieningen_wandel_legenda.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/voorzieningen_zorg.map&request=getcapabilities&service=wms&version=1.1.30'|grep-vdefault|grepName>voorzieningen_zorg.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/waterdieptes.map&request=getcapabilities&service=wms&version=1.1.31'|grep-vdefault|grepName>waterdieptes.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/water.map&request=getcapabilities&service=wms&version=1.1.32'|grep-vdefault|grepName>water.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/water_overstromingsmodel.map&request=getcapabilities&service=wms&version=1.1.33'|grep-vdefault|grepName>water_overstromingsmodel.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/welvaart_2010.map&request=getcapabilities&service=wms&version=1.1.34'|grep-vdefault|grepName>welvaart_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/welvaart.map&request=getcapabilities&service=wms&version=1.1.35'|grep-vdefault|grepName>welvaart.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/wereld_gezondheid.map&request=getcapabilities&service=wms&version=1.1.36'|grep-vdefault|grepName>wereld_gezondheid.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/wereld_milieu.map&request=getcapabilities&service=wms&version=1.1.37'|grep-vdefault|grepName>wereld_milieu.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/wereld_transport.map&request=getcapabilities&service=wms&version=1.1.38'|grep-vdefault|grepName>wereld_transport.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/wereld_welvaart.map&request=getcapabilities&service=wms&version=1.1.39'|grep-vdefault|grepName>wereld_welvaart.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/wonen_2010.map&request=getcapabilities&service=wms&version=1.1.40'|grep-vdefault|grepName>wonen_2010.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/wonen.map&request=getcapabilities&service=wms&version=1.1.41'|grep-vdefault|grepName>wonen.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/zeeuwse_delta.map&request=getcapabilities&service=wms&version=1.1.42'|grep-vdefault|grepName>zeeuwse_delta.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/zuiderzeeland.map&request=getcapabilities&service=wms&version=1.1.43'|grep-vdefault|grepName>zuiderzeeland.map
curl'http://mapserver.edugis.nl/cgi-bin/mapserv?map=maps/edugis/cache/zuid_limburg.map&request=getcapabilities&service=wms&version=1.1.44'|grep-vdefault|grepName>zuid_limburg.map